#!/bin/bash
#
# script to help doing a release
#
# debian/patches/release
#   is harmless, it can be reverted
#
# debian/patches/release unpatch
#   reverts the "release" changes
#
# debian/patches/release 4.3.2-1
#   sets the version number and deletes the original files
#

function regular_release_changes
{
 mv debian/changelog debian/changelog.orig
 sed -e '1s/UNRELEASED/unstable/' \
     -e '3s/expecting //' \
     -e '3s/version .*$/version/' \
     -e '4d' \
     debian/changelog.orig > debian/changelog

 echo Don\'t forgot to update the NEWS file.
}

if [ "x" == "x${1}" ]
then
 regular_release_changes
else
 case "${1}" in
  unpatch)
   test -f debian/changelog.orig && mv debian/changelog.orig debian/changelog
  ;;
  *\.*\.*-*)
   regular_release_changes
   # set version and current date
   VERSION=${1}
   RFC2822DATE=$(date -R)
   mv debian/changelog debian/changelog.orig
   sed -e "1s/\(.*\) (\(.*\)) \(.*\)/\1 ($VERSION) \3/" \
       -e "1,/ -- /s/>  .*/>  $RFC2822DATE/" \
       debian/changelog.orig > debian/changelog
   # plus a clean up
   rm debian/changelog.orig
  ;;
  *)
   echo \'${1}\' is an unsupported subcommand
   echo "Supported subcommands are: unpatch & *.*.*-*"
   echo " Where * are digits for the version"
  ;;
 esac
fi

# end of script ( happy hacking/testing the package )
