#!/bin/sh
#
#  ugly hack to fix #123360
#
#
## don't known how doc/reference/conglomerate.types.bkp is build
#
cp doc/reference/conglomerate.types.bkp doc/reference/conglomerate.types
#
# don't if the above works, yes this is work in progress
# if it does, a nice automatic solutions would be
#
# having  doc/reference/conglomerate.types.in
# with
#  @include(conglomerate.types.bkp) or something like that
#
# and in top source dir configure.in (configure.ac?)
# AC_OUTPUT(doc/reference/conglomerate.types)
#
