#!/bin/bash

patched_make_distcheck ()
{
# there something wrong with write permission on a computer of gst
# this patch should be removed
GCONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=yes make distcheck &
sleep 15 # guessed time for make dist
sleep 30 # guessed time for a far amount of building
chmod -R +w conglomerate-0.?.*
wait
ST=$?
echo $ST
return $ST
}

./autogen.sh
# GCONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=yes make distcheck
patched_make_distcheck
if [ $? -ne 0 ]
then
 echo make distcheck failed
 exit 1
fi

TARBALL=$( ls -t *.tar.gz | head -1 )
echo put here commands for uploading ${TARBALL}

# eof
