#!/bin/bash

./autogen.sh
GCONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=yes make distcheck
if [ $? -ne 0 ]
then
 echo make distcheck failed
 exit 1
fi

TARBALL=$( ls -t *.tar.gz | head -1 )
echo put here commands for uploading ${TARBALL}

# eof
