#!/bin/bash
# make cvs tarball
# script to make a tarball from the version control source tree (CVS, SVN, etc)
# it exists because the generated Makefiles do many check which aren't passed 
# With the cheats in this script is a `make dist` possible

# temporary modified files
TMPMOD="configure.ac ChangeLog"

# intltool isn't yet configured right
for intfile in extract merge update
do
  if=intltool-${intfile}.in
  [ ! -f ${if} ] && touch ${if}
done

# preserve
for TM in ${TMPMOD}
do
  cp -p ${TM} ${TM}.tm
done

if [ "x${1}" != "x" ]
then
  # it is a prerelease
  # modify them
  ( date -R; echo "This is prelease ${1}"; echo; cat ChangeLog.tm ) > ChangeLog
  sed -e "s/^AC_INIT(\(.*\), \(.*\))/AC_INIT(\1, \2pre${1})/" \
      -e "/doc\/reference/d" \
    configure.ac.tm > configure.ac
else
  sed -e "/doc\/reference/d" \
    configure.ac.tm > configure.ac
fi

# don't spent time on the poor gtk-doc stuff
mv doc/Makefile.am doc/Makefile.am.withGtkDoc
sed -e 's/SUBDIRS = \(.*\)reference\(.*\)/SUBDIRS = \1 \2/' doc/Makefile.am.withGtkDoc > doc/Makefile.am

# regenerate the makefile
# (needed to create "pre" in the tarball name and skipping doc/reference)
./autogen.sh

# make the tarball and check it
GCONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=yes make distcheck
if [ $? -ne 0 ]
then
 echo *********************
 echo make distcheck failed
 echo *********************
fi

# restore the temporary modified files
for TM in ${TMPMOD}
do
  mv ${TM}.tm ${TM}
done
mv doc/Makefile.am.withGtkDoc doc/Makefile.am

# show the MD5 checksum of the fresh tarball
md5sum $( ls -t *.tar.gz | head -1 )

# eof
