#!/bin/bash

# Generates the files needed for correct gtkdoc output in doc/reference:
# conglomerate.types, conglomerate-overrides.txt, conglomerate-sections.txt
# Robert Varga, 2003-10.28

######################################################
# VARIABLES
# All paths are relative to the main conglomerate dir
# except for 
######################################################

# the directory containing the C sources
SOURCE_DIR=src
# the directory containing the gtkdoc-generated output
DEST_DIR=doc/reference
# We need to remember this path, because we call gtkdoc-scan in doc/reference,
# as it outputs other files besides $CONGLOMERATE_SECTIONS
WORK_DIR=$PWD
# Files that we create
CONGLOMERATE_TYPES=conglomerate.types
CONGLOMERATE_OVERRIDES=conglomerate-overrides.txt
CONGLOMERATE_SECTIONS=conglomerate-sections.txt
# Sometimes we have ChangeLog, sometimes Changelog
CHANGELOG=ChangeLog

# ChangeLog output
CHANGELOG_DATE=`date +%F`
# is a name necessary in the ChangeLog?
CHANGELOG_EMAIL='Robert Varga <frozenfingersxs4all.nl>'
CHANGELOG_FILES='conglomerate.types, conglomerate-overrides.txt, conglomerate-sections.txt:'
CHANGELOG_NOTICE='uss/mkgtkdoc: Syncronized with source'

UPDATE_FALSE=F
UPDATE_TRUE=T
UPDATE_DOCS=$UPDATE_FALSE
# UPDATE_MESSAGE=


#######################################
# First, check if we need to update
#######################################
if [ ! -e $DEST_DIR/$CONGLOMERATE_TYPES ]
then
    UPDATE_DOCS=$UPDATE_TRUE 
    echo '*** UPDATE REQUIRED: conglomerate.types not found ***'
fi
if [ ! -e $DEST_DIR/$CONGLOMERATE_OVERRIDES ]
then
    UPDATE_DOCS=$UPDATE_TRUE
    echo '*** UPDATE REQUIRED: conglomerate-overrides.txt not found ***'
fi
if [ ! -e $DEST_DIR/$CONGLOMERATE_SECTIONS ]
then
    UPDATE_DOCS=$UPDATE_TRUE
    echo '*** UPDATE REQUIRED: conglomerate-sections.txt not found ***'
fi

# Simple test using conglomerate.types
# Should we use the source files' date stamps instead?
if [[ $UPDATE_DOCS = $UPDATE_FALSE ]]
then
    for HEADERFILE in $SOURCE_DIR/*.h
    do
	if [[ $HEADERFILE != "$SOURCE_DIR/cong-editor-widget3-impl.h" ]]
	then
	    HBASE=`basename $HEADERFILE`
		if [[ `grep -c $HBASE $DEST_DIR/$CONGLOMERATE_TYPES` -eq "0" ]]
		then
		    UPDATE_DOCS=$UPDATE_TRUE
		    echo '*** UPDATE REQUIRED: conglomerate.types is out of sync ***'
    		    break
    		fi
    	fi
    done
fi

###############################
# Proceed with update if needed
###############################
[[ $UPDATE_DOCS = $UPDATE_FALSE ]] && echo '*** All gtkdoc files are up to date. Exit ***'
[[ $UPDATE_DOCS = $UPDATE_FALSE ]] && exit 0

##################################
# Generation of conglomerate.types
##################################

DEST_TYPES=$DEST_DIR/$CONGLOMERATE_TYPES

echo '*** Generating conglomerate.types ***'
# remove the old conglomerate.types
test -e $DEST_TYPES && rm -f $DEST_TYPES
echo '#include "global.h"' > $DEST_TYPES
for HEADERFILE in $SOURCE_DIR/*.h
do 
	if [[  $HEADERFILE != "$SOURCE_DIR/cong-editor-widget3-impl.h" && $HEADERFILE != "$SOURCE_DIR/global.h" ]]
	then
		echo "#include \"`basename $HEADERFILE`\"" >> $DEST_TYPES
	fi
done
echo >> $DEST_TYPES
# here we have a hack that outputs cong_editor_widget3_get_type istead of cong_editor_widget_get_type
# (found in cong-editor-widget.h)
# also, we ignore cong-editor-widget3-impl.h and global.h
let OBJNUM=0
for HEADERFILE in $SOURCE_DIR/*.h
do
	if [[ $HEADERFILE != "$SOURCE_DIR/cong-editor-widget3-impl.h" && $HEADERFILE != "$SOURCE_DIR/global.h" ]]
	then
		A=`grep 'get_type' $HEADERFILE | grep -v '#define'`
		if [[ $A != "" ]]
		then
			B=`echo $A | sed '{s/\ .void.;//g}'`
			if [[ $B = "cong_editor_widget_get_type" ]]
			then
				echo 'cong_editor_widget3_get_type' >> $DEST_TYPES
			else
				echo $B >> $DEST_TYPES
			fi
			let OBJNUM+=1
		fi
	fi
done
echo '*** Found '$OBJNUM' object declarations ***'

##########################################
# Generation of conglomerate-overrides.txt
##########################################

DEST_OVERRIDES=$DEST_DIR/$CONGLOMERATE_OVERRIDES

echo '*** Generating conglomerate-overrides.txt ***'
# Remove the old overrides file, because we generate a new one, in case objects got added/removed from the sources
test -e $DEST_OVERRIDES && rm -f $DEST_OVERRIDES
# get_types
# note that cong-editor-widget3-impl.h conflicts with other headers (generating duplicate
# decalration errors), so we skip it.
let OBJNUM=0
for HEADERFILE in $SOURCE_DIR/*.h
do
	HBASE=`basename $HEADERFILE`
	if [[ $HBASE != "global.h" && $HBASE != "*.h" && $HBASE != "cong-editor-widget3-impl.h" ]]
	then
		if [[ `grep -c 'get_type' $HEADERFILE` -ne 0 ]]
		then
			A=`grep -e 'get_type' $HEADERFILE | grep -v "#define"`
			B=${A%%_get_type (void);}
			C=`echo $B | sed -e {s/_//g}`
			D=`grep -i "struct $C" $HEADERFILE | grep -v "Class" | grep -v Details | grep -v typedef | sed {s/struct\ //1}`
			if [[ $D != "" ]]
			then
				echo '<STRUCT>' >> $DEST_OVERRIDES
				echo '<NAME>'$D'</NAME>' >> $DEST_OVERRIDES
				echo '</STRUCT>' >> $DEST_OVERRIDES
				echo 'Added '$D
				let OBJNUM+=1
			fi
		fi
	fi
done
echo '*** Added '$OBJNUM' objects to conglomerate-overrides.txt ***'

############################################################
# Generation of conglomerate-sections.txt, using gtkdoc-scan
############################################################

SOURCE_OVERRIDES=$DEST_DIR/$CONGLOMERATE_OVERRIDES
DEST_SECTIONS=$DEST_DIR/$CONGLOMERATE_SECTIONS
SOURCE_SECTIONS=$DEST_SECTIONS
# source dir relative to $WORK_DIR, for use with gtkdoc-scan
SOURCE_DIR=$WORK_DIR/src

echo '*** Generating conglomerate-sections.txt ***'
# remove old conglomerate.types if exists
test -e $DEST_SECTIONS && rm -f $DEST_SECTIONS
cd $DEST_DIR
gtkdoc-scan --module=conglomerate --source-dir=$SOURCE_DIR --ignore-headers=""
cd $WORK_DIR

# check for gtkdoc-scan output
if [ ! -e $DEST_SECTIONS ]
then
    echo '*** ERROR: conglomerate-sections.txt not found. ***'
    echo '*** please report this to frozenfingers@xs4all.nl ***'
    exit 1
fi

FILE_LINE=
CONG_SECTIONS=`cat $SOURCE_SECTIONS`
# Now that we have the file's contents, delete the file
test -e $SOURCE_SECTIONS && rm -f $SOURCE_SECTIONS
let OBJNUM=0
for LINE in $CONG_SECTIONS
do
	[[ `echo "$LINE" | grep "<FILE>"` != "" ]] && FILE_LINE=`echo "$LINE" | grep "<FILE>"`
	A=`expr match "$LINE" '.*_TYPE'`
	if [[ $A != "0" ]]
	then
		FILENAME=$SOURCE_DIR/`echo $FILE_LINE | sed {s/\<FILE\>//g} | sed {s/\<.FILE\>//g}`.h
		FALSEOBJNAME=`echo $LINE | sed {s/_//g} | sed {s/TYPE//g}`
		REALOBJNAME=`grep -i "<.*>$FALSEOBJNAME<.*>" $SOURCE_OVERRIDES | sed {s/\<NAME\>//g} | sed {s/\<.*NAME\>//g}`
		echo '<TITLE>'$REALOBJNAME'</TITLE>' >> $DEST_SECTIONS
		echo $REALOBJNAME >> $DEST_SECTIONS
		echo 'Added '$REALOBJNAME
		let OBJNUM+=1
	else
		# test to preserve the empty lines
		if [[ $LINE = '<SECTION>' ]]
		then
		    echo >> $DEST_SECTIONS
		fi
		echo $LINE >> $DEST_SECTIONS
	fi
done
echo '*** Added '$OBJNUM' objects to conglomerate-sections.txt ***'
echo '*** The gtkdoc files were uccessfuly created ***'

############################
# Update the ChangeLog
############################

mv $DEST_DIR/$CHANGELOG $DEST_DIR/$CHANGELOG.tmp
echo $CHANGELOG_DATE'  '$CHANGELOG_EMAIL >> $DEST_DIR/$CHANGELOG
# echo $CHANGELOG_EMAIL >> $DEST_DIR/$CHANGELOG
echo >> $DEST_DIR/$CHANGELOG
echo -e '\t* '$CHANGELOG_FILES >> $DEST_DIR/$CHANGELOG
echo -e '\t'$CHANGELOG_NOTICE >> $DEST_DIR/$CHANGELOG
echo >> $DEST_DIR/$CHANGELOG

cat $DEST_DIR/$CHANGELOG.tmp >> $DEST_DIR/$CHANGELOG
rm -f $DEST_DIR/$CHANGELOG.tmp

echo -e '\a*** '$CHANGELOG' updated ***'

exit 0
