#!/bin/bash

# source dir = path to the header files
# SOURCE_DIR=../src
SOURCE_DIR=$1
# dest output = the path including conglomerate-overrides.txt
# DEST_OVERRIDES=../doc/reference/conglomerate-overrides.txt
DEST_OVERRIDES=$2

if [ $# -ne 2 ]
then
	# probably no parameters supplied, setting them
	SOURCE_DIR=src
	DEST_OVERRIDES=doc/reference/conglomerate-overrides.txt
fi

[ -e $DEST_OVERRIDES ] && mv $DEST_OVERRIDES $DEST_OVERRIDES.bak

echo '*** Generating conglomerate-overrides.txt ***'

# get_types
# note that cong-editor-widget3-impl.h conflicts with other headers (generating duplicate
# decalration errors), so we skip it.

let OBJNUM=0
for HEADERFILE in $SOURCE_DIR/*.h
do
	HBASE=`basename $HEADERFILE`
	if [[ $HBASE != "global.h" && $HBASE != "*.h" && $HBASE != "cong-editor-widget3-impl.h" ]]
	then
		if [[ `grep -c 'get_type' $HEADERFILE` -ne 0 ]]
		then
			A=`grep -e 'get_type' $HEADERFILE | grep -v "#define"`
			B=${A%%_get_type (void);}
			C=`echo $B | sed -e {s/_//g}`
			D=`grep -i "struct $C" $HEADERFILE | grep -v "Class" | grep -v Details | grep -v typedef | sed {s/struct\ //1}`
			if [[ $D != "" ]]
			then
				echo '<STRUCT>' >> $DEST_OVERRIDES
				echo '<NAME>'$D'</NAME>' >> $DEST_OVERRIDES
				echo '</STRUCT>' >> $DEST_OVERRIDES
				echo 'Added '$D
				let OBJNUM+=1
			fi
		fi
	fi
done
echo '*** Added '$OBJNUM' objects to conglomerate-overrides.txt ***'
