#!/bin/bash

# Generates the files needed for correct gtkdoc output in doc/reference:
# conglomerate.types, conglomerate-overrides.txt, conglomerate-sections.txt
# Robert Varga, 2003-10.28

######################################################
# VARIABLES
# All paths are relative to the main conglomerate dir
# except for 
######################################################

# the directory containing the C sources
SOURCE_DIR=src
# the directory containing the gtkdoc-generated output
DEST_DIR=doc/reference
# We need to remember this path, because we call gtkdoc-scan in doc/reference,
# as it outputs other files besides $CONGLOMERATE_SECTIONS
WORK_DIR=$PWD
# Files that we create
CONGLOMERATE_TYPES=conglomerate.types
CONGLOMERATE_OVERRIDES=conglomerate-overrides.txt
CONGLOMERATE_SECTIONS=conglomerate-sections.txt
# Sometimes we have ChangeLog, sometimes Changelog
CHANGELOG=ChangeLog

# ChangeLog output
CHANGELOG_DATE=`date +%F`
# is a name necessary in the ChangeLog?
CHANGELOG_EMAIL='Robert Varga <frozenfingersxs4all.nl>'
CHANGELOG_FILES='conglomerate.types, conglomerate-overrides.txt, conglomerate-sections.txt:'
CHANGELOG_NOTICE='uss/mkgtkdoc: Syncronized with source'

UPDATE_FALSE=F
UPDATE_TRUE=T
UPDATE_DOCS=$UPDATE_FALSE
# UPDATE_MESSAGE=


#######################################

uss/mkgtkdocoverrides
uss/mkgtkdocsections
uss/mkgtkdoctypes
# hoping the sequence is the smart one FIXME

###
# wish:
# update of doc/reference/ChangeLog FIXME
