#!/bin/bash

# source dir = the path to the header files
SOURCE_DIR=$1
# output file = the path including conglomerate.types
DEST_TYPES=$2

# no args => default paths from top
if [ $# -ne 2 ]
then
    SOURCE_DIR=src
    DEST_TYPES=doc/reference/conglomerate.types
fi

# copy the old $DEST_TYPES to $DEST_TYPES.bak
[ -e $DEST_TYPES ] && mv $DEST_TYPES $DEST_TYPES.bak

echo '*** Generating conglomerate.types ***'

echo '#include "global.h"' > $DEST_TYPES
for HEADERFILE in $SOURCE_DIR/*.h
do 
	if [[  $HEADERFILE != "$SOURCE_DIR/cong-editor-widget3-impl.h" && $HEADERFILE != "$SOURCE_DIR/global.h" ]]
	then
		echo "#include \"`basename $HEADERFILE`\"" >> $DEST_TYPES
	fi
done
echo >> $DEST_TYPES
# here we have a hack that outputs cong_editor_widget3_get_type istead of cong_editor_widget_get_type
# (found in cong-editor-widget.h)
# also, we ignore cong-editor-widget3-impl.h and global.h
let OBJNUM=0
for HEADERFILE in $SOURCE_DIR/*.h
do
	if [[ $HEADERFILE != "$SOURCE_DIR/cong-editor-widget3-impl.h" && $HEADERFILE != "$SOURCE_DIR/global.h" ]]
	then
		A=`grep 'get_type' $HEADERFILE | grep -v '#define'`
		if [[ $A != "" ]]
		then
			B=`echo $A | sed '{s/\ .void.;//g}'`
			if [[ $B = "cong_editor_widget_get_type" ]]
			then
				echo 'cong_editor_widget3_get_type' >> $DEST_TYPES
			else
				echo $B >> $DEST_TYPES
			fi
			let OBJNUM+=1
		fi
	fi
done
echo '*** Found '$OBJNUM' object declarations'
