#!/bin/bash

echo script currently disabled
exit 1

# source dir = path to the header files
SOURCE_DIR=$1
# destination dir
DEST_DIR=$2
# source file: path including conglomerate-overrides.txt
SOURCE_OVERRIDES=$3
# dest output = path including conglomerate-sections.txt
DEST_SECTIONS=$4

# In the case that we are not called with exactly 3 arguments
# default the paths from top conglomerate dir
if [ $# -ne 4 ]
then
    SOURCE_DIR=src
    DEST_DIR=doc/reference
    SOURCE_OVERRIDES=doc/reference/conglomerate-overrides.txt
    DEST_SECTIONS=doc/reference/conglomerate-sections.txt
fi

WORK_DIR=$PWD

[ -e $DEST_SECTIONS ] && mv $DEST_SECTIONS $DEST_SECTIONS.bak

cd $DEST_DIR
# assumes SOURCE_DIR is relative
gtkdoc-scan --module=conglomerate --source-dir=$WORK_DIR/$SOURCE_DIR --ignore-headers=""
cd $WORK_DIR

# check for gtkdoc-scan output
if [ ! -e $DEST_SECTIONS ]
then
    echo '*** ERROR: conglomerate-sections.txt not found. ***'
    echo '*** please report this to frozenfingers@xs4all.nl ***'
    exit 1
fi

echo '*** Generating conglomerate-sections.txt ***'

FILE_LINE=
CONG_SECTIONS=`cat $DEST_SECTIONS`
# Now that we have the file's contents, delete the file
test -e $DEST_SECTIONS && rm -f $DEST_SECTIONS

let OBJNUM=0
for LINE in $CONG_SECTIONS
do
	[[ `echo "$LINE" | grep "<FILE>"` != "" ]] && FILE_LINE=`echo "$LINE" | grep "<FILE>"`
	A=`expr match "$LINE" '.*_TYPE'`
	if [[ $A != "0" ]]
	then
		FILENAME=$SOURCE_DIR/`echo $FILE_LINE | sed {s/\<FILE\>//g} | sed {s/\<.FILE\>//g}`.h
		OBJNAME=`echo $LINE | sed {s/_//g} | sed {s/TYPE//g}`
		D=`grep -i "<.*>$OBJNAME<.*>" $SOURCE_OVERRIDES | sed {s/\<NAME\>//g} | sed {s/\<.*NAME\>//g}`
		echo '<TITLE>'$D'</TITLE>' >> $DEST_SECTIONS
		echo $D >> $DEST_SECTIONS
		echo 'Added '$D
		let OBJNUM+=1
	else
	    # preserve empty lines
		if [[ $LINE = '<SECTION>' ]]
		then
		    echo >> $DEST_SECTIONS
		fi
		echo $LINE >> $DEST_SECTIONS
	fi
done
echo 'Added '$OBJNUM' objects to conglomerate-sections.txt'
