#!/bin/bash

# Generates the files needed for correct gtkdoc output in doc/reference:
# conglomerate.types, conglomerate-overrides.txt, conglomerate-sections.txt
# Robert Varga, 2003-10.28

######################################################
# VARIABLES
# All paths are relative to the main conglomerate dir
######################################################

# the directory containing the C sources
SOURCE_DIR=src
# the directory containing the gtkdoc-generated output
DEST_DIR=doc/reference
# We need to remember this path, because we call gtkdoc-scan in doc/reference,
# as it outputs other files besides $CONGLOMERATE_SECTIONS
WORK_DIR=$PWD
# Files that we create
CONGLOMERATE_TYPES=conglomerate.types
CONGLOMERATE_OVERRIDES=conglomerate-overrides.txt
CONGLOMERATE_SECTIONS=conglomerate-sections.txt

# Sometimes we have ChangeLog, sometimes Changelog
CHANGELOG=ChangeLog
# ChangeLog output
CHANGELOG_DATE=`date +%F`
# is a name necessary in the ChangeLog?
CHANGELOG_EMAIL='Robert Varga <frozenfingersxs4all.nl>'

update_gtkdoc_changelog(){
    
    CHANGELOG_FILE=$1
    CHANGELOG_NOTICE=$2

    mv $DEST_DIR/$CHANGELOG $DEST_DIR/$CHANGELOG.tmp
    echo `date +%F`'  '$CHANGELOG_EMAIL > $DEST_DIR/$CHANGELOG
    echo >> $DEST_DIR/$CHANGELOG
    echo -e '\t* '$CHANGELOG_FILE':' >> $DEST_DIR/$CHANGELOG
    echo -e '\t'$CHANGELOG_NOTICE >> $DEST_DIR/$CHANGELOG
    echo >> $DEST_DIR/$CHANGELOG
    cat $DEST_DIR/$CHANGELOG.tmp >> $DEST_DIR/$CHANGELOG
    rm -f $DEST_DIR/$CHANGELOG.tmp

    echo -e '\a*** '$CHANGELOG' updated ***'

}

######################################

uss/mkgtkdoctypes $SOURCE_DIR $DEST_DIR/$CONGLOMERATE_TYPES 

if [ `diff $DEST_DIR/$CONGLOMERATE_TYPES $DEST_DIR/$CONGLOMERATE_TYPES.bak | wc -l` -ne 0 ]
then
    # update ChangeLog
    update_gtkdoc_changelog 'conglomerate.types' 'Syncronized with source by uss/mkgtkdoctypes $version: 1.1$'
fi

uss/mkgtkdocoverrides $SOURCE_DIR $DEST_DIR/$CONGLOMERATE_OVERRIDES

if [ `diff $DEST_DIR/$CONGLOMERATE_OVERRIDES $DEST_DIR/$CONGLOMERATE_OVERRIDES.bak | wc -l` -ne 0 ]
then
    # update ChangeLog
    update_gtkdoc_changelog 'conglomerate-overrides.txt' 'Syncronized with source by uss/mkgtkdocoverrides $version: 1.1$'
fi

uss/mkgtkdocsections $SOURCE_DIR $DEST_DIR $DEST_DIR/$CONGLOMERATE_OVERRIDES $DEST_DIR/$CONGLOMERATE_SECTIONS

if [ `diff $DEST_DIR/$CONGLOMERATE_SECTIONS $DEST_DIR/$CONGLOMERATE_SECTIONS.bak | wc -l` -ne 0 ]
then
    # update ChangeLog
    update_gtkdoc_changelog 'conglomerate-sections.txt' 'Syncronized with source by uss/mkgtkdocsections $version: 1.3$'
fi

rm -f $DEST_DIR/*.bak
