#!/bin/bash
#
# how to update config.sub and config.guess
# updated version of these files in the tarball
# makes it easy to compile them on the many architectures
#
#
# wget ftp://ftp.gnu.org/gnu/config/config.guess
# wget ftp://ftp.gnu.org/gnu/config/config.sub
