/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 8; tab-width: 8 -*- */

#include <gtk/gtk.h>

#include "global.h"
#include "cong-error-dialog.h"

/**
 * cong_error_test_file_ops:
 * @parent_window:
 * @filename:
 * @vfs_result:
 *
 * TODO: Write me
 */
void 
cong_error_test_file_ops(GtkWindow *parent_window, 
			 GFile *file,
			 GError *error)
{
	GtkDialog* dialog;
	char *filename;

	gsize file_size = 5*1024*1024; /* 5 megabytes, for a test */

	filename = g_file_get_basename(file);

	g_message(_("Testing File->Open failure of \"%s\" with result %s"), filename, error->message);

	dialog = cong_error_dialog_new_from_file_open_failure_with_gerror(parent_window, file, error);
	cong_error_dialog_run(GTK_DIALOG(dialog));		
	gtk_widget_destroy(GTK_WIDGET(dialog));    

	g_message(_("Testing File->Save failure of \"%s\" with result %s"), filename, error->message);

	dialog = cong_error_dialog_new_from_file_save_failure(parent_window, file, error, &file_size);
	cong_error_dialog_run(GTK_DIALOG(dialog));		
	gtk_widget_destroy(GTK_WIDGET(dialog));    

	g_message(_("Testing generic failure of \"%s\" with result %s"), filename, error->message);

	dialog = cong_error_dialog_new_from_file_operation_failure(parent_window,
								   _("Conglomerate is simulating the failure of a generic file operation."),
								   file,
								   error,
								   _("This dialog was generated by the automated testing routine"));
	cong_error_dialog_run(GTK_DIALOG(dialog));		
	gtk_widget_destroy(GTK_WIDGET(dialog));
	g_free(filename);
}

#if GLIB_CHECK_VERSION(2,26,0)
#define LAST_ERROR G_IO_ERROR_PROXY_NOT_ALLOWED
#elif GLIB_CHECK_VERSION(2,24,0)
#define LAST_ERROR G_IO_ERROR_INVALID_DATA
#elif GLIB_CHECK_VERSION(2,22,0)
#define LAST_ERROR G_IO_ERROR_ADDRESS_IN_USE
#else
#define LAST_ERROR G_IO_ERROR_TOO_MANY_OPEN_FILES
#endif

/**
 * cong_error_tests:
 * @parent_window:
 *
 * TODO: Write me
 */
void 
cong_error_tests(GtkWindow *parent_window)
{
	GError *error;
	GFile *file;
	int i;
	for (i=(int)G_IO_ERROR_FAILED;i<(int)LAST_ERROR;i++) {

		#define TEST_URI ("file:///home/david/test.xml")
		// #define TEST_URI ("file:///home/david/fubar.xml")
		// #define TEST_URI ("file:///home/david/faq.html")
		// #define TEST_URI ("http://www.fubar.com/fubar.xml")
		// #define TEST_URI ("ftp://www.fubar.com/fubar.xml")

		error = g_error_new(G_IO_ERROR, i, "Test message");
		file = g_file_new_for_uri(TEST_URI);

		cong_error_test_file_ops(parent_window, 
					 file,
					 error);
		g_object_unref(file);
	}
}
