/* XPM */
char *icon_new[] = {
/* width height ncolors chars_per_pixel */
"36 36 55 1",
/* colors */
"  c #000000",
". c #BEBEA3",
"X c #A2A298",
"o c #C9C9A7",
"O c #ADAD9C",
"+ c #D0D0AA",
"@ c #B4B49F",
"# c #DDDDB0",
"$ c #BFBFA3",
"% c #A3A398",
"& c #AEAE9C",
"* c #D7D7AD",
"= c #AAAA9B",
"- c #B7B7A1",
"; c #CDCDA9",
": c #B1B19E",
"> c #BCBCA2",
", c #A0A097",
"< c #B8B8A1",
"1 c #C3C3A5",
"2 c #A7A79A",
"3 c #B2B29E",
"4 c #E9E981",
"5 c #CACAA8",
"6 c #909090",
"7 c #B9B9A1",
"8 c #C4C4A5",
"9 c #A8A89A",
"0 c #D1D1AB",
"q c #B5B5A0",
"w c #FF9090",
"e c #B3B39E",
"r c #E9E99E",
"t c #C0C0A4",
"y c #A2A297",
"u c #CDCDAA",
"i c None",
"p c #E9E9CF",
"a c None",
"s c #ABAB9C",
"d c #A9A99A",
"f c #CF6060",
"g c #D2D2AB",
"h c #B6B6A0",
"j c #C1C1A4",
"k c #CECEAA",
"l c #B0B09D",
"z c #A00000",
"x c #D9D9AE",
"c c #BDBDA3",
"v c #C8C8A7",
"b c #ACAC9C",
"n c #B7B7A0",
"m c #C4C4A6",
"M c #C2C2A4",
/* pixels */
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaiiaiaiaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaiappapapaiaaaaaaaaaaaaaa",
"aaaaaaaaaaaiaparrrrapaiaaaaaaaaaaaaa",
"aaaaaaaaaaiapar4 44rrpapaaaaaaaaaaaa",
"aaaaaaaaaiapar4 w  44rrapaiaaaaaaaaa",
"aaaaaaaaiapar4 wwww  44rrpaiaaaaaaaa",
"aaaaaaaiapar4 wwwwwww  44rpaiaaaaaaa",
"aaaaaaiapar4 wwwwwwwwww  4rpaiaaaaaa",
"aaaaaaapar4 wwwwwwwwwwwwz 4rpaaaaaaa",
"aaaaaaiar4 wwwwwwwwwwwwzz 4raiaaaaaa",
"aaaaaaapr4 aawwwwwwwwwzzz 4rpaaaaaaa",
"aaaaaaiar4 ffaawwwwwwzzzz 4raiaaaaaa",
"aaaaaaapr4 ffffaawwwzzzzz 4rpaaaaaaa",
"aaaaaaiar4 ffffffaazzzzzz 4raiaaaaaa",
"aaaaaaapr4 ffffffffzzzzzz 4rpaaaaaaa",
"aaaaaaiar4 ffffffffzzzzzz 4raiaaaaaa",
"aaaaaaapr4 ffffffffzzzzzz 4rpaaaaaaa",
"aaaaaaiar4 ffffffffzzzzzz 4raiaaaaaa",
"aaaaaaapr4 ffffffffzzzzz 4rapaaaaaaa",
"aaaaaaiar4  fffffffzzzz 4rapaiaaaaaa",
"aaaaaaaprr44  fffffzzz 4rapaiaaaaaaa",
"aaaaaaiaparr44  fffzz 4rapaiaaaaaaaa",
"aaaaaaaiapaprr44  fz 4rapaiaaaaaaaaa",
"aaaaaaaaiaiapa####  ###paiaaaaaaaaaa",
"aaaaaaaaaaaia##########*;aaaaaaaaaaa",
"aaaaaaaaaaaa50x######*0oj7aaaaaaaaaa",
"aaaaaaaaaaan.m5k0gg+uv1chaaaaaaaaaaa",
"aaaaaaaaaad&e<>t181M$>-3aaaaaaaaaaaa",
"aaaaaaaaaaaa=&:@hnhqelOaaaaaaaaaaaaa",
"aaaaaaaaaaaaaa9=sbs=d2aaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaX%Xy,aaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaa66aaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
};
