#!/bin/bash
#
#  Script to start build a debian package
#  Copyright 2003 by Geert Stappers under the terms of GPL v2.0
#


if [ "G${0}" != "Gdeb/build" ]
then
  echo We expect you to run this script as \`deb/build\`
  echo  to make sure you are in the toplevel directory of this project.
  exit 1
fi

if [ ! -x ./configure ]
then
  echo Assuming you did a fresh CVS checkout,
  echo gonna run \`./autogen.sh\` for you to create the initial Makefiles.
  ./autogen.sh
fi

DEBIAN_FILES="rules control changelog copyright docs compat
 conglomerate.menu conglomerate_icon.xpm
 NEWS watch"

#
if [ ! -f debian/control ]
then
  # directories that we will use
  mkdir -p debian/patches
  echo coping  deb directory into debian
  for DF in ${DEBIAN_FILES}
  do
    cp deb/${DF} debian
  done
  echo copy also the patch files
  cp deb/patches/P* debian/patches
fi

#
if [ ! -x debian/rules ]
then
  chmod +x debian/rules
fi

# assuming the user has debian development stuff installed
# ( this is the place where a test on such executables should done )


#
if [ $# > 1 ]
then
  # the only supported parameter.
  dch -v "$1" "New upstream release."
fi

echo gonna build the package
if [ ! -f build-stamp ]
then
  dpkg-buildpackage -uc -us
else
  debian/rules binary
fi


echo one directory level up, are these .deb files:
ls -ltr ../*.deb

# end of script
